In [5]:
import numpy as np

y_true = np.array([21,20.1,22.8,55,19.34])
y_pred = np.array([21.5,22.5,7.32,12,20.53])
ss_res = np.sum((y_true - y_pred) ** 2)
ss_tot = np.sum((y_true - np.mean(y_true))**2)
r_squared = 1 - (ss_res / ss_tot)

n = len(y_true)
p = 3

adj_r_squared = 1- (1 - r_squared) * ((n-1)/ (n - p -1))
r_squared
adj_r_squared

np.float64(-7.90209580945136)

In [7]:
data = np.array([[10, 20,30], [21, 3,9], [8, 1,3], [15, 41, 55]])

cov_matrix = np.cov(data, rowvar = False)
cov_matrix

array([[ 33.66666667,   2.83333333,   9.5       ],
       [  2.83333333, 344.91666667, 436.25      ],
       [  9.5       , 436.25      , 554.25      ]])

In [13]:

# Example data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Calculate the correlation matrix
corr_matrix = np.corrcoef(x, y)
print(corr_matrix)
# Output: [[1. 1.] [1. 1.]]

# Extract the correlation coefficient
r = corr_matrix[0, 1]  # or corr_matrix[1, 0]
print(r) # Output: 1.0   

[[1. 1.]
 [1. 1.]]
0.9999999999999999


In [10]:
sample_binomial = np.random.binomial(10, 0.5, 10000)
sample_binomial

array([6, 5, 6, ..., 4, 6, 6], shape=(10000,))

In [14]:
sample_normal = np.random.normal(0.0, 1.0,1000)
sample_normal

array([ 1.73434922e-01, -4.06146384e-02, -1.49699250e+00, -1.45292251e+00,
       -4.47923737e-02, -7.49211044e-01,  5.42032014e-01, -6.74735264e-01,
       -1.10727873e+00,  1.68981041e+00, -7.37748650e-02, -4.26837861e-01,
        2.98853452e-01, -6.50937569e-01, -1.22705840e+00,  3.58925278e+00,
        1.18460782e+00,  3.19701091e-01,  6.88502759e-01,  4.76982148e-01,
       -1.04086110e+00,  1.51131928e+00, -1.11768715e+00,  1.24932286e+00,
       -5.73240493e-01, -5.81772415e-01,  5.95236849e-02,  2.43619425e-01,
        1.29811077e+00, -6.10311525e-01,  2.51531396e-01,  6.92039303e-02,
        2.95523795e-01, -9.75713191e-01, -8.22476773e-01,  6.07799859e-01,
       -1.70665499e-01,  7.08466443e-01, -9.23308161e-01,  3.52643597e-01,
        1.51658720e-01,  1.52540740e-02,  8.73535924e-01, -2.08540665e-01,
        4.13765776e-01, -8.78921825e-01,  1.37146843e+00,  2.34408683e-02,
        5.66279357e-01,  3.12177536e-01, -8.36845334e-01,  2.83151228e-01,
       -7.68825965e-01, -

In [16]:
def ks_shift(expected, actual):
    vals = np.sort(np.unique(np.concatenate([expected, actual])))
    cdf_e = np.searchsorted(np.sort(expected), vals, side='right')/len(expected)
    cdf_a = np.searchsorted(np.sort(actual), vals, side='right')/len(actual)
    return np.max(np.abs(cdf_e - cdf_a))

train_data = np.random.normal(0, 1, 1000)
test_data = np.random.normal(0.5, 1.2, 1000)
ks_stat = ks_shift(train_data, test_data)
ks_stat

np.float64(0.20000000000000007)